Update workflow file

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -106,130 +106,130 @@ jobs:
             tar -xzf code.tar.gz
             rm code.tar.gz
           }
-#       - name: Setup Go 1.24
-#         if: runner.os == 'Windows'
-#         uses: actions/setup-go@v5
-#         with:
-#           go-version: 1.24
-#
-#       - name: Install MinGW-w64
-#         if: runner.os == 'Windows'
-#         shell: pwsh
-#         run: |
-#           # 下载指定版本的MinGW-w64
-#           Invoke-WebRequest -Uri "https://github.com/niXman/mingw-builds-binaries/releases/download/15.1.0-rt_v12-rev0/x86_64-15.1.0-release-posix-seh-ucrt-rt_v12-rev0.7z" -OutFile "mingw-w64.7z"
-#
-#           # 创建目标文件夹
-#           $mingwPath = "C:\a\mingw64"
-#           if (!(Test-Path $mingwPath)) {
-#               New-Item -Path $mingwPath -ItemType Directory
-#           }
-#
-#           # 解压文件
-#           7z x mingw-w64.7z -o"$mingwPath" -y
-#
-#           # 设置环境变量
-#           echo "MinGW_HOME=$mingwPath" >> $env:GITHUB_ENV
-#           echo "$mingwPath\bin" >> $env:GITHUB_PATH
-#
-#           # 验证安装
-#           gcc -v
-#
-#       - name: Compile libclash.dll
-#         if: runner.os == 'Windows'
-#         working-directory: clash_flt2/fclash
-#         shell: pwsh
-#         run: |
-#           chmod a+x ./build_libclash_win.sh
-#           bash ./build_libclash_win.sh
-#
-#           Copy-Item -Path "dist/libclash.dll" -Destination "${{ github.workspace }}\${{ env.APP_DIRNAME }}\windows\"
-#           Get-ChildItem "${{ github.workspace }}\${{ env.APP_DIRNAME }}\windows\"
-#       - name: Set up Flutter
-#         uses: subosito/flutter-action@v2
-#         with:
-#           flutter-version: '3.24.5'
-#           channel: "stable"
-#
-#       - name: Set up JDK 8
-#         uses: actions/setup-java@v4
-#         with:
-#           distribution: 'temurin'
-#           java-version: '17'
-#       - name: Setup Android SDK
-#         uses: android-actions/setup-android@v3
-#
-#       - name: Flutter pub get
-#         run: |
-#           flutter clean
-#           flutter pub get
-#           flutter pub run build_runner build
-#         working-directory: ${{ env.APP_DIRNAME }}
-#
-#       - name: Build app
-#         run: ${{ matrix.build_cmd }}
-#         working-directory: ${{ env.APP_DIRNAME }}
-#
-#       # 非 Windows: 处理 artifact
-#       - name: Prepare artifact (Unix/macOS)
-#         if: runner.os != 'Windows'
-#         shell: bash
-#         run: |
-#           mkdir -p dist
-#           OS_NAME=${{ matrix.platform }}
-#           FILE_NAME="${APP_NAME}_${APP_DIGITAL_VERSION}.${{ matrix.artifact_ext }}"
-#           if [ "${{ matrix.artifact_ext }}" = "zip" ]; then
-#             cd "${{ matrix.artifact_path}}/.."
-#             zip -r "../../../../../../dist/$FILE_NAME" "${APP_NAME_ZH}.app"
-#           else
-#             cp "${{ matrix.artifact_path }}" "dist/$FILE_NAME"
-#           fi
-#       - name: Install Inno Setup
-#         if: runner.os == 'Windows'
-#         run: |
-#           $ErrorActionPreference = "Stop"
-#           $url = "https://jrsoftware.org/download.php/is.exe"
-#           $output = "$env:TEMP\innosetup.exe"
-#           Invoke-WebRequest -Uri $url -OutFile $output
-#           Start-Process -Wait -FilePath $output -ArgumentList "/VERYSILENT", "/SUPPRESSMSGBOXES", "/NORESTART", "/SP-"
-#           echo "C:\Program Files (x86)\Inno Setup 6" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
-#
-#       - name: Download Inno Setup Simplified Chinese Language File
-#         if: runner.os == 'Windows'
-#         run: |
-#           $ErrorActionPreference = "Stop"
-#
-#           $langDir = "C:\Program Files (x86)\Inno Setup 6\Languages"
-#           if (!(Test-Path $langDir)) {
-#             Write-Error "Inno Setup not found at expected path: $langDir"
-#             exit 1
-#           }
-#
-#           Invoke-WebRequest `
-#             -Uri "https://raw.githubusercontent.com/kira-96/Inno-Setup-Chinese-Simplified-Translation/main/ChineseSimplified.isl" `
-#             -OutFile "$langDir\ChineseSimplified.isl"
-#
-#           Write-Host "Downloaded ChineseSimplified.isl to $langDir"
-#
-#       - name: Inno Setup
-#         if: runner.os == 'Windows'
-#         shell: pwsh
-#         run: |
-#           ISCC.exe ${{ env.APP_DIRNAME }}\AssembleWinSetup.iss
-#       - name: Get built EXE full path and save to EXE_FILE
-#         if: runner.os == 'Windows'
-#         shell: pwsh
-#         run: |
-#           $exe = Get-ChildItem "${{ matrix.artifact_path }}\..\" -Filter *.exe | Select-Object -First 1
-#           if (-not $exe) {
-#             Write-Error "No .exe file found in the runner directory."
-#             exit 1
-#           }
-#
-#           $exePath = $exe.FullName
-#           echo "EXE_FILE=$exePath" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
-#
-#           Write-Host "Found EXE full path: $exePath"
+      - name: Setup Go 1.24
+        if: runner.os == 'Windows'
+        uses: actions/setup-go@v5
+        with:
+          go-version: 1.24
+
+      - name: Install MinGW-w64
+        if: runner.os == 'Windows'
+        shell: pwsh
+        run: |
+          # 下载指定版本的MinGW-w64
+          Invoke-WebRequest -Uri "https://github.com/niXman/mingw-builds-binaries/releases/download/15.1.0-rt_v12-rev0/x86_64-15.1.0-release-posix-seh-ucrt-rt_v12-rev0.7z" -OutFile "mingw-w64.7z"
+
+          # 创建目标文件夹
+          $mingwPath = "C:\a\mingw64"
+          if (!(Test-Path $mingwPath)) {
+              New-Item -Path $mingwPath -ItemType Directory
+          }
+
+          # 解压文件
+          7z x mingw-w64.7z -o"$mingwPath" -y
+
+          # 设置环境变量
+          echo "MinGW_HOME=$mingwPath" >> $env:GITHUB_ENV
+          echo "$mingwPath\bin" >> $env:GITHUB_PATH
+
+          # 验证安装
+          gcc -v
+
+      - name: Compile libclash.dll
+        if: runner.os == 'Windows'
+        working-directory: clash_flt2/fclash
+        shell: pwsh
+        run: |
+          chmod a+x ./build_libclash_win.sh
+          bash ./build_libclash_win.sh
+
+          Copy-Item -Path "dist/libclash.dll" -Destination "${{ github.workspace }}\${{ env.APP_DIRNAME }}\windows\"
+          Get-ChildItem "${{ github.workspace }}\${{ env.APP_DIRNAME }}\windows\"
+      - name: Set up Flutter
+        uses: subosito/flutter-action@v2
+        with:
+          flutter-version: '3.24.5'
+          channel: "stable"
+
+      - name: Set up JDK 8
+        uses: actions/setup-java@v4
+        with:
+          distribution: 'temurin'
+          java-version: '17'
+      - name: Setup Android SDK
+        uses: android-actions/setup-android@v3
+
+      - name: Flutter pub get
+        run: |
+          flutter clean
+          flutter pub get
+          flutter pub run build_runner build
+        working-directory: ${{ env.APP_DIRNAME }}
+
+      - name: Build app
+        run: ${{ matrix.build_cmd }}
+        working-directory: ${{ env.APP_DIRNAME }}
+
+      # 非 Windows: 处理 artifact
+      - name: Prepare artifact (Unix/macOS)
+        if: runner.os != 'Windows'
+        shell: bash
+        run: |
+          mkdir -p dist
+          OS_NAME=${{ matrix.platform }}
+          FILE_NAME="${APP_NAME}_${APP_DIGITAL_VERSION}.${{ matrix.artifact_ext }}"
+          if [ "${{ matrix.artifact_ext }}" = "zip" ]; then
+            cd "${{ matrix.artifact_path}}/.."
+            zip -r "../../../../../../dist/$FILE_NAME" "${APP_NAME_ZH}.app"
+          else
+            cp "${{ matrix.artifact_path }}" "dist/$FILE_NAME"
+          fi
+      - name: Install Inno Setup
+        if: runner.os == 'Windows'
+        run: |
+          $ErrorActionPreference = "Stop"
+          $url = "https://jrsoftware.org/download.php/is.exe"
+          $output = "$env:TEMP\innosetup.exe"
+          Invoke-WebRequest -Uri $url -OutFile $output
+          Start-Process -Wait -FilePath $output -ArgumentList "/VERYSILENT", "/SUPPRESSMSGBOXES", "/NORESTART", "/SP-"
+          echo "C:\Program Files (x86)\Inno Setup 6" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
+
+      - name: Download Inno Setup Simplified Chinese Language File
+        if: runner.os == 'Windows'
+        run: |
+          $ErrorActionPreference = "Stop"
+
+          $langDir = "C:\Program Files (x86)\Inno Setup 6\Languages"
+          if (!(Test-Path $langDir)) {
+            Write-Error "Inno Setup not found at expected path: $langDir"
+            exit 1
+          }
+
+          Invoke-WebRequest `
+            -Uri "https://raw.githubusercontent.com/kira-96/Inno-Setup-Chinese-Simplified-Translation/main/ChineseSimplified.isl" `
+            -OutFile "$langDir\ChineseSimplified.isl"
+
+          Write-Host "Downloaded ChineseSimplified.isl to $langDir"
+
+      - name: Inno Setup
+        if: runner.os == 'Windows'
+        shell: pwsh
+        run: |
+          ISCC.exe ${{ env.APP_DIRNAME }}\AssembleWinSetup.iss
+      - name: Get built EXE full path and save to EXE_FILE
+        if: runner.os == 'Windows'
+        shell: pwsh
+        run: |
+          $exe = Get-ChildItem "${{ matrix.artifact_path }}\..\" -Filter *.exe | Select-Object -First 1
+          if (-not $exe) {
+            Write-Error "No .exe file found in the runner directory."
+            exit 1
+          }
+
+          $exePath = $exe.FullName
+          echo "EXE_FILE=$exePath" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
+
+          Write-Host "Found EXE full path: $exePath"
       # Windows: 处理 artifact
       - name: Prepare artifact (Windows)
         if: runner.os == 'Windows'
@@ -237,25 +237,23 @@ jobs:
         run: |
           mkdir -p dist
           mkdir -p tmp
-          ls .\app\assets\windows\
 
           $ext = "${{ matrix.artifact_ext }}"
           $fileName = "${{ env.APP_NAME }}_${{ env.APP_DIGITAL_VERSION }}_${{ matrix.platform }}.${ext}"
           $newExe = "${{ env.APP_NAME }}_${{ env.APP_DIGITAL_VERSION }}.exe"
-          #Copy-Item -Path "${{ env.EXE_FILE }}" -Destination ".\tmp\${newExe}"
-          #Copy-Item -Path ".\app\assets\windows\*" -Destination ".\tmp\"
-          #Compress-Archive -Path ".\tmp\*" -DestinationPath ".\dist\${fileName}" -Force
-
-#       # 上传到 MinIO
-#       - name: Upload to MinIO
-#         shell: pwsh
-#         run: |
-#           if ($IsWindows) {
-#             "${{ env.APP_DIGITAL_VERSION }}" > .\vp_last_build_version
-#             ./mc.exe cp --recursive ".\dist\" "myminio/${{ env.MINIO_BUCKET }}/release/vp/"
-#             ./mc.exe cp vp_last_build_version "myminio/${{ env.MINIO_BUCKET }}/release/"
-#           } else {
-#             echo "${{ env.APP_DIGITAL_VERSION }}" > vp_last_build_version
-#             mc cp --recursive ./dist/ myminio/${{ env.MINIO_BUCKET }}/release/vp/
-#             mc cp vp_last_build_version myminio/${{ env.MINIO_BUCKET }}/release/
-#           }
+          Copy-Item -Path "${{ env.EXE_FILE }}" -Destination ".\tmp\${newExe}"
+          Copy-Item -Path ".\app\assets\windows\*" -Destination ".\tmp\"
+          Compress-Archive -Path ".\tmp\*" -DestinationPath ".\dist\${fileName}" -Force
+      # 上传到 MinIO
+      - name: Upload to MinIO
+        shell: pwsh
+        run: |
+          if ($IsWindows) {
+            "${{ env.APP_DIGITAL_VERSION }}" > .\vp_last_build_version
+            ./mc.exe cp --recursive ".\dist\" "myminio/${{ env.MINIO_BUCKET }}/release/vp/"
+            ./mc.exe cp vp_last_build_version "myminio/${{ env.MINIO_BUCKET }}/release/"
+          } else {
+            echo "${{ env.APP_DIGITAL_VERSION }}" > vp_last_build_version
+            mc cp --recursive ./dist/ myminio/${{ env.MINIO_BUCKET }}/release/vp/
+            mc cp vp_last_build_version myminio/${{ env.MINIO_BUCKET }}/release/
+          }
