Update workflow file

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -107,84 +107,84 @@ jobs:
           mv app base_app
           curl -qs "${{ secrets.API_ASSETS_URL }}/build.sh" -o ./base_app/.gitea/workflows/assets/build.sh
           chmod a+x ./base_app/.gitea/workflows/assets/build.sh
-      - name: Setup Go 1.24
-        if: runner.os == 'Windows'
-        uses: actions/setup-go@v5
-        with:
-          go-version: 1.24
-
-      - name: Install MinGW-w64
-        if: runner.os == 'Windows'
-        shell: pwsh
-        run: |
-          # 下载指定版本的MinGW-w64
-          Invoke-WebRequest -Uri "https://github.com/niXman/mingw-builds-binaries/releases/download/15.1.0-rt_v12-rev0/x86_64-15.1.0-release-posix-seh-ucrt-rt_v12-rev0.7z" -OutFile "mingw-w64.7z"
-
-          # 创建目标文件夹
-          $mingwPath = "C:\a\mingw64"
-          if (!(Test-Path $mingwPath)) {
-              New-Item -Path $mingwPath -ItemType Directory
-          }
-
-          # 解压文件
-          7z x mingw-w64.7z -o"$mingwPath" -y
-
-          # 设置环境变量
-          echo "MinGW_HOME=$mingwPath" >> $env:GITHUB_ENV
-          echo "$mingwPath\bin" >> $env:GITHUB_PATH
-
-          # 验证安装
-          gcc -v
-
-      - name: Compile libclash.dll
-        if: runner.os == 'Windows'
-        working-directory: clash_flt2/fclash
-        shell: pwsh
-        run: |
-          chmod a+x ./build_libclash_win.sh
-          bash ./build_libclash_win.sh
-
-          Copy-Item -Path "dist/libclash.dll" -Destination "${{ github.workspace }}\base_app\windows\"
-          Get-ChildItem "${{ github.workspace }}\base_app\windows\"
-      - name: Set up Flutter
-        uses: subosito/flutter-action@v2
-        with:
-          flutter-version: '3.24.5'
-          channel: "stable"
-
-      - name: Set up JDK 8
-        uses: actions/setup-java@v4
-        with:
-          distribution: 'temurin'
-          java-version: '17'
-      - name: Setup Android SDK
-        uses: android-actions/setup-android@v3
-      - name: Install Inno Setup
-        if: runner.os == 'Windows'
-        run: |
-          $ErrorActionPreference = "Stop"
-          $url = "https://jrsoftware.org/download.php/is.exe"
-          $output = "$env:TEMP\innosetup.exe"
-          Invoke-WebRequest -Uri $url -OutFile $output
-          Start-Process -Wait -FilePath $output -ArgumentList "/VERYSILENT", "/SUPPRESSMSGBOXES", "/NORESTART", "/SP-"
-          echo "C:\Program Files (x86)\Inno Setup 6" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
-
-      - name: Download Inno Setup Simplified Chinese Language File
-        if: runner.os == 'Windows'
-        run: |
-          $ErrorActionPreference = "Stop"
-
-          $langDir = "C:\Program Files (x86)\Inno Setup 6\Languages"
-          if (!(Test-Path $langDir)) {
-            Write-Error "Inno Setup not found at expected path: $langDir"
-            exit 1
-          }
-
-          Invoke-WebRequest `
-            -Uri "https://raw.githubusercontent.com/kira-96/Inno-Setup-Chinese-Simplified-Translation/main/ChineseSimplified.isl" `
-            -OutFile "$langDir\ChineseSimplified.isl"
-
-          Write-Host "Downloaded ChineseSimplified.isl to $langDir"
+#       - name: Setup Go 1.24
+#         if: runner.os == 'Windows'
+#         uses: actions/setup-go@v5
+#         with:
+#           go-version: 1.24
+#
+#       - name: Install MinGW-w64
+#         if: runner.os == 'Windows'
+#         shell: pwsh
+#         run: |
+#           # 下载指定版本的MinGW-w64
+#           Invoke-WebRequest -Uri "https://github.com/niXman/mingw-builds-binaries/releases/download/15.1.0-rt_v12-rev0/x86_64-15.1.0-release-posix-seh-ucrt-rt_v12-rev0.7z" -OutFile "mingw-w64.7z"
+#
+#           # 创建目标文件夹
+#           $mingwPath = "C:\a\mingw64"
+#           if (!(Test-Path $mingwPath)) {
+#               New-Item -Path $mingwPath -ItemType Directory
+#           }
+#
+#           # 解压文件
+#           7z x mingw-w64.7z -o"$mingwPath" -y
+#
+#           # 设置环境变量
+#           echo "MinGW_HOME=$mingwPath" >> $env:GITHUB_ENV
+#           echo "$mingwPath\bin" >> $env:GITHUB_PATH
+#
+#           # 验证安装
+#           gcc -v
+#
+#       - name: Compile libclash.dll
+#         if: runner.os == 'Windows'
+#         working-directory: clash_flt2/fclash
+#         shell: pwsh
+#         run: |
+#           chmod a+x ./build_libclash_win.sh
+#           bash ./build_libclash_win.sh
+#
+#           Copy-Item -Path "dist/libclash.dll" -Destination "${{ github.workspace }}\base_app\windows\"
+#           #ls "${{ github.workspace }}\base_app\windows\"
+#       - name: Set up Flutter
+#         uses: subosito/flutter-action@v2
+#         with:
+#           flutter-version: '3.24.5'
+#           channel: "stable"
+#
+#       - name: Set up JDK 8
+#         uses: actions/setup-java@v4
+#         with:
+#           distribution: 'temurin'
+#           java-version: '17'
+#       - name: Setup Android SDK
+#         uses: android-actions/setup-android@v3
+#       - name: Install Inno Setup
+#         if: runner.os == 'Windows'
+#         run: |
+#           $ErrorActionPreference = "Stop"
+#           $url = "https://jrsoftware.org/download.php/is.exe"
+#           $output = "$env:TEMP\innosetup.exe"
+#           Invoke-WebRequest -Uri $url -OutFile $output
+#           Start-Process -Wait -FilePath $output -ArgumentList "/VERYSILENT", "/SUPPRESSMSGBOXES", "/NORESTART", "/SP-"
+#           echo "C:\Program Files (x86)\Inno Setup 6" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
+#
+#       - name: Download Inno Setup Simplified Chinese Language File
+#         if: runner.os == 'Windows'
+#         run: |
+#           $ErrorActionPreference = "Stop"
+#
+#           $langDir = "C:\Program Files (x86)\Inno Setup 6\Languages"
+#           if (!(Test-Path $langDir)) {
+#             Write-Error "Inno Setup not found at expected path: $langDir"
+#             exit 1
+#           }
+#
+#           Invoke-WebRequest `
+#             -Uri "https://raw.githubusercontent.com/kira-96/Inno-Setup-Chinese-Simplified-Translation/main/ChineseSimplified.isl" `
+#             -OutFile "$langDir\ChineseSimplified.isl"
+#
+#           Write-Host "Downloaded ChineseSimplified.isl to $langDir"
 
       - name: Build app
         run: |
